export const avatarPresets = [
  {
    id: "teacher-f-rose",
    name: "캐릭터 1",
    backgroundFrom: "#ffe1ef",
    backgroundTo: "#ffd4dd",
    skin: "#f3c7a6",
    hair: "#5a3642",
    shirt: "#d85c7b",
    accent: "#ffd8e3",
    hairStyle: "bob",
    accessory: "clip",
  },
  {
    id: "teacher-f-mint",
    name: "캐릭터 2",
    backgroundFrom: "#d9fff3",
    backgroundTo: "#d4f3ff",
    skin: "#f2c4a0",
    hair: "#314f63",
    shirt: "#28b49d",
    accent: "#f8fff9",
    hairStyle: "long",
    accessory: "none",
  },
  {
    id: "teacher-f-violet",
    name: "캐릭터 3",
    backgroundFrom: "#efe3ff",
    backgroundTo: "#dcd7ff",
    skin: "#f0c9aa",
    hair: "#483561",
    shirt: "#7a63d9",
    accent: "#f8f3ff",
    hairStyle: "bun",
    accessory: "earring",
  },
  {
    id: "teacher-f-sky",
    name: "캐릭터 4",
    backgroundFrom: "#d8ecff",
    backgroundTo: "#d7f7ff",
    skin: "#efc6a2",
    hair: "#3c445e",
    shirt: "#4f88f2",
    accent: "#eef8ff",
    hairStyle: "pony",
    accessory: "star",
  },
  {
    id: "teacher-m-navy",
    name: "캐릭터 5",
    backgroundFrom: "#d9e7ff",
    backgroundTo: "#cfe0ff",
    skin: "#efc59d",
    hair: "#27354a",
    shirt: "#426db7",
    accent: "#eff6ff",
    hairStyle: "crop",
    accessory: "none",
  },
  {
    id: "teacher-m-amber",
    name: "캐릭터 6",
    backgroundFrom: "#ffe8c7",
    backgroundTo: "#fff0d8",
    skin: "#eec09b",
    hair: "#5d3e2a",
    shirt: "#d9822b",
    accent: "#fff7ea",
    hairStyle: "side",
    accessory: "glasses",
  },
  {
    id: "teacher-m-forest",
    name: "캐릭터 7",
    backgroundFrom: "#d6f4db",
    backgroundTo: "#e1ffef",
    skin: "#efc7a5",
    hair: "#2f4337",
    shirt: "#2d8a53",
    accent: "#f4fff6",
    hairStyle: "parted",
    accessory: "none",
  },
  {
    id: "teacher-m-plum",
    name: "캐릭터 8",
    backgroundFrom: "#ecdfff",
    backgroundTo: "#f8e7ff",
    skin: "#efc7a8",
    hair: "#4c3558",
    shirt: "#8d5acf",
    accent: "#f9f0ff",
    hairStyle: "wave",
    accessory: "star",
  },
  {
    id: "teacher-n-cloud",
    name: "캐릭터 9",
    backgroundFrom: "#e4eef8",
    backgroundTo: "#edf6ff",
    skin: "#efc8a7",
    hair: "#4b5664",
    shirt: "#70889f",
    accent: "#ffffff",
    hairStyle: "soft",
    accessory: "none",
  },
  {
    id: "teacher-n-coral",
    name: "캐릭터 10",
    backgroundFrom: "#ffe2d8",
    backgroundTo: "#fff0ea",
    skin: "#f0c7a6",
    hair: "#5d4851",
    shirt: "#ea7458",
    accent: "#fff8f5",
    hairStyle: "round",
    accessory: "clip",
  },
  {
    id: "teacher-c-lime",
    name: "캐릭터 11",
    backgroundFrom: "#e5ffd4",
    backgroundTo: "#f4ffd8",
    skin: "#f0c8a2",
    hair: "#42533a",
    shirt: "#7bbf3d",
    accent: "#fbfff2",
    hairStyle: "crop",
    accessory: "star",
  },
  {
    id: "teacher-c-indigo",
    name: "캐릭터 12",
    backgroundFrom: "#dbe2ff",
    backgroundTo: "#e8ebff",
    skin: "#efc7a6",
    hair: "#2f355f",
    shirt: "#5d6fe8",
    accent: "#f5f7ff",
    hairStyle: "long",
    accessory: "earring",
  },
] as const;

export type AvatarPreset = (typeof avatarPresets)[number];
export type AvatarPresetId = AvatarPreset["id"];

export const defaultAvatarPreset: AvatarPresetId = avatarPresets[0].id;

export function getAvatarPreset(presetId?: AvatarPresetId) {
  if (!presetId) {
    return avatarPresets[0];
  }

  return avatarPresets.find((preset) => preset.id === presetId) ?? avatarPresets[0];
}
