export const avatarPresets = [
  {
    id: "teacher-f-rose",
    name: "로즈",
    backgroundFrom: "#fde1f0",
    backgroundTo: "#f9c7d9",
    glow: "#fff3f8",
    skin: "#f2c9a7",
    skinShadow: "#e2aa84",
    hair: "#5c3045",
    hairShine: "#8f5a71",
    outerwear: "#c84d71",
    innerwear: "#fff6fb",
    accent: "#ffd3df",
    hairStyle: "soft-bob",
    outfitStyle: "blazer",
    accessory: "clip",
    eyeStyle: "soft",
    mouthStyle: "smile",
    backdropStyle: "halo",
  },
  {
    id: "teacher-f-mint",
    name: "민트",
    backgroundFrom: "#dbfff1",
    backgroundTo: "#cdeff9",
    glow: "#f5fffb",
    skin: "#efc6a2",
    skinShadow: "#ddac83",
    hair: "#34576b",
    hairShine: "#5d8195",
    outerwear: "#2ba88d",
    innerwear: "#f7fffd",
    accent: "#d9fff6",
    hairStyle: "long-wave",
    outfitStyle: "cardigan",
    accessory: "none",
    eyeStyle: "bright",
    mouthStyle: "grin",
    backdropStyle: "arc",
  },
  {
    id: "teacher-f-violet",
    name: "바이올렛",
    backgroundFrom: "#efe6ff",
    backgroundTo: "#dcd5ff",
    glow: "#f8f4ff",
    skin: "#f0c8a9",
    skinShadow: "#dda880",
    hair: "#4e3868",
    hairShine: "#7d62a1",
    outerwear: "#7357d7",
    innerwear: "#fbf8ff",
    accent: "#efe8ff",
    hairStyle: "top-bun",
    outfitStyle: "coat",
    accessory: "earring",
    eyeStyle: "focus",
    mouthStyle: "calm",
    backdropStyle: "ribbon",
  },
  {
    id: "teacher-f-sky",
    name: "스카이",
    backgroundFrom: "#d8eeff",
    backgroundTo: "#d2fbff",
    glow: "#f4fbff",
    skin: "#efc7a6",
    skinShadow: "#dea97f",
    hair: "#3f4966",
    hairShine: "#6f7a9f",
    outerwear: "#4c89eb",
    innerwear: "#eef7ff",
    accent: "#cfe4ff",
    hairStyle: "pony-tail",
    outfitStyle: "jacket",
    accessory: "star",
    eyeStyle: "smile",
    mouthStyle: "smile",
    backdropStyle: "sparkle",
  },
  {
    id: "teacher-m-navy",
    name: "네이비",
    backgroundFrom: "#dde6ff",
    backgroundTo: "#cfdfff",
    glow: "#eef3ff",
    skin: "#efc59e",
    skinShadow: "#dcaa80",
    hair: "#26364b",
    hairShine: "#4b5f7a",
    outerwear: "#4268b4",
    innerwear: "#f6f9ff",
    accent: "#dfe9ff",
    hairStyle: "classic-part",
    outfitStyle: "blazer",
    accessory: "none",
    eyeStyle: "focus",
    mouthStyle: "calm",
    backdropStyle: "panel",
  },
  {
    id: "teacher-m-amber",
    name: "앰버",
    backgroundFrom: "#ffe7cf",
    backgroundTo: "#fff0dc",
    glow: "#fff8ef",
    skin: "#edc19b",
    skinShadow: "#d9a172",
    hair: "#61412d",
    hairShine: "#8a6247",
    outerwear: "#d68633",
    innerwear: "#fff7ef",
    accent: "#ffe6c8",
    hairStyle: "soft-crop",
    outfitStyle: "knit",
    accessory: "glasses",
    eyeStyle: "soft",
    mouthStyle: "smile",
    backdropStyle: "halo",
  },
  {
    id: "teacher-m-forest",
    name: "포레스트",
    backgroundFrom: "#daf2df",
    backgroundTo: "#e5fff0",
    glow: "#f7fff9",
    skin: "#efc6a4",
    skinShadow: "#dca882",
    hair: "#324539",
    hairShine: "#5a7264",
    outerwear: "#2f8a56",
    innerwear: "#f7fff8",
    accent: "#d8f1df",
    hairStyle: "slick-side",
    outfitStyle: "cardigan",
    accessory: "none",
    eyeStyle: "focus",
    mouthStyle: "calm",
    backdropStyle: "arc",
  },
  {
    id: "teacher-m-plum",
    name: "플럼",
    backgroundFrom: "#ecdfff",
    backgroundTo: "#f7e9ff",
    glow: "#fcf4ff",
    skin: "#efc8a7",
    skinShadow: "#dca67e",
    hair: "#50345d",
    hairShine: "#78538d",
    outerwear: "#8e5ccc",
    innerwear: "#fbf7ff",
    accent: "#eadbff",
    hairStyle: "short-wave",
    outfitStyle: "coat",
    accessory: "pin",
    eyeStyle: "bright",
    mouthStyle: "grin",
    backdropStyle: "ribbon",
  },
  {
    id: "teacher-n-cloud",
    name: "클라우드",
    backgroundFrom: "#e3edf8",
    backgroundTo: "#edf6ff",
    glow: "#fafdff",
    skin: "#efc8a8",
    skinShadow: "#dca882",
    hair: "#4d5868",
    hairShine: "#758293",
    outerwear: "#70869b",
    innerwear: "#fbfdff",
    accent: "#ffffff",
    hairStyle: "straight-lob",
    outfitStyle: "jacket",
    accessory: "none",
    eyeStyle: "soft",
    mouthStyle: "smile",
    backdropStyle: "panel",
  },
  {
    id: "teacher-n-coral",
    name: "코랄",
    backgroundFrom: "#ffe3d8",
    backgroundTo: "#fff0ea",
    glow: "#fff8f5",
    skin: "#f0c7a7",
    skinShadow: "#dca87f",
    hair: "#5c4a53",
    hairShine: "#876b77",
    outerwear: "#e57158",
    innerwear: "#fff7f3",
    accent: "#ffd9ce",
    hairStyle: "rounded-bob",
    outfitStyle: "coat",
    accessory: "clip",
    eyeStyle: "smile",
    mouthStyle: "smile",
    backdropStyle: "sparkle",
  },
  {
    id: "teacher-c-lime",
    name: "라임",
    backgroundFrom: "#e7ffd8",
    backgroundTo: "#f5ffd6",
    glow: "#fbfff2",
    skin: "#efc8a3",
    skinShadow: "#d9a97d",
    hair: "#44573a",
    hairShine: "#718d5f",
    outerwear: "#79ba42",
    innerwear: "#fbfff6",
    accent: "#e3f6cc",
    hairStyle: "curly-short",
    outfitStyle: "knit",
    accessory: "star",
    eyeStyle: "bright",
    mouthStyle: "grin",
    backdropStyle: "dots",
  },
  {
    id: "teacher-c-indigo",
    name: "인디고",
    backgroundFrom: "#dbe3ff",
    backgroundTo: "#e9ecff",
    glow: "#f5f7ff",
    skin: "#efc7a7",
    skinShadow: "#dca87d",
    hair: "#30406b",
    hairShine: "#5b6e9f",
    outerwear: "#5a6fe3",
    innerwear: "#f8faff",
    accent: "#d7defd",
    hairStyle: "long-braid",
    outfitStyle: "blazer",
    accessory: "earring",
    eyeStyle: "focus",
    mouthStyle: "calm",
    backdropStyle: "halo",
  },
  {
    id: "teacher-c-cocoa",
    name: "코코아",
    backgroundFrom: "#f7e6db",
    backgroundTo: "#f0d8cb",
    glow: "#fff8f3",
    skin: "#c98a62",
    skinShadow: "#ab6d49",
    hair: "#2f231f",
    hairShine: "#5a463f",
    outerwear: "#7f4d3f",
    innerwear: "#fff7f2",
    accent: "#e8cbbd",
    hairStyle: "coily-round",
    outfitStyle: "cardigan",
    accessory: "glasses",
    eyeStyle: "smile",
    mouthStyle: "smile",
    backdropStyle: "dots",
  },
  {
    id: "teacher-c-aqua",
    name: "아쿠아",
    backgroundFrom: "#d8f7ff",
    backgroundTo: "#d5ebff",
    glow: "#f3fdff",
    skin: "#f0c7a5",
    skinShadow: "#dca77e",
    hair: "#35516d",
    hairShine: "#5f84a8",
    outerwear: "#2f9dc1",
    innerwear: "#f5fdff",
    accent: "#d7f4ff",
    hairStyle: "side-lob",
    outfitStyle: "jacket",
    accessory: "headset",
    eyeStyle: "focus",
    mouthStyle: "grin",
    backdropStyle: "arc",
  },
  {
    id: "teacher-c-sunset",
    name: "선셋",
    backgroundFrom: "#ffe0c9",
    backgroundTo: "#ffd3e6",
    glow: "#fff6ef",
    skin: "#edc29e",
    skinShadow: "#d79e74",
    hair: "#6c3c32",
    hairShine: "#9a6155",
    outerwear: "#de6a73",
    innerwear: "#fff8f6",
    accent: "#ffd7c8",
    hairStyle: "volumn-wave",
    outfitStyle: "coat",
    accessory: "clip",
    eyeStyle: "soft",
    mouthStyle: "smile",
    backdropStyle: "ribbon",
  },
  {
    id: "teacher-c-olive",
    name: "올리브",
    backgroundFrom: "#ecf5d7",
    backgroundTo: "#deeac5",
    glow: "#fbfff2",
    skin: "#d7a37d",
    skinShadow: "#bc8561",
    hair: "#39412c",
    hairShine: "#68754f",
    outerwear: "#6f8750",
    innerwear: "#f8fced",
    accent: "#e8f4cf",
    hairStyle: "neat-short",
    outfitStyle: "blazer",
    accessory: "pin",
    eyeStyle: "bright",
    mouthStyle: "calm",
    backdropStyle: "panel",
  },
] as const;

export type AvatarPreset = (typeof avatarPresets)[number];
export type AvatarPresetId = AvatarPreset["id"];

export const defaultAvatarPreset: AvatarPresetId = avatarPresets[0].id;

export function getAvatarPreset(presetId?: AvatarPresetId) {
  if (!presetId) {
    return avatarPresets[0];
  }

  return avatarPresets.find((preset) => preset.id === presetId) ?? avatarPresets[0];
}
